### ISSUE TITLE
Bsb not found, ocamlmerlin won't run

### ISSUE THREAD

**Issue by Fabs** [reasonml-editor/reasonml-idea-plugin#10]
First of all thanks for the great plugin.

I installed this plugin on intelij eap, I used the instructions to install bs-platform and reasonml from the reason documentation [0,1,2]. My IntelliJ have the following two problems:

``` 
Error locating merlin. Can't find merlin, using 'ocamlmerlin'. Cannot run program "ocamlmerlin": error=2, No such file or directory
``` 

```
Bsb: Bsb is disabled, you need to manually launch an external process
```

First, one thing I think might be a problem is the merlin version, instructions here [2] tell I should have merlin 2.5.x which contradicts the merling 3+ need on this plugin. But unfortunally being new to ocaml and reasonml I failed to get the right version with ocaml and opam to get merlin 3.

Any direction so I can solve this issue?

Thanks a lot.

[0] - npm install -g https://github.com/reasonml/reason-cli/archive/beta-v-1.13.7-bin-darwin.tar.gz
[1] - npm install -g bs-platform
[2] - https://reasonml.github.io/guide/editor-tools/global-installation

**Comment by giraud** [comment]
Hi,

having a working environment is not a nice developer experience.

First, you can't use reason-cli because it comes with merlin 2 only.
You need to install reason and merlin through opam (the alternative in https://reasonml.github.io/guide/editor-tools/global-installation). once you have switched to opam 4.02.3 you can do `opam install reason.1.13.7 merlin.3.0.2` to install both tools.

The first message tells you that merlin is not found by the plugin. You need to add an entry in your vm properties file `-DreasonMerlin=<absolute path to ocamlmerlin>` for the plugin to find it.

The second message also tells you that the bucklescript compiler is not found by the plugin. Same, you need to add an entry in your vm properties file `-DreasonBsb=node_modules/bs-platform/bin/bsb.exe`, if you have installed bucklescript locally to your project.
