### ISSUE TITLE
Syntax errors not reported

### ISSUE THREAD

**Issue by villesau** [reasonml-editor/reasonml-idea-plugin#129]
plugin version: v0.69

### Description

Looks like no matter what's written, no errors are reported. You can reproduce the issue by cloning https://github.com/facebook/flow and intently typoing something.

Also missing variables etc are not reported. Are you planning on bringing proper Merlin support to the plugin? That would probably help in most of the cases and make the plugin much more useful.

**Comment by giraud** [comment]
Hi, I'm happy you are using the plugin but you must be aware that I started this plugin to have a good DX in ReasonML and I focus my (rare free) time on that aspect. 

I added some lightweight integration with ocaml at the source level (mainly parsing/highlighting) because it was needed for ReasonML, and because - to my surprise - more and more people seem to need it. But right now it's still a side project of the plugin.

The compiler aspect is not really worked/implemented for ocaml, and that's why you don't have any feedback. That's something I want to improve, but I don't expect to work on it soon. I need to prioritize a lot !

For that kind of stuff you might have more success with https://github.com/sidharthkuruvila/ocaml-ide, but I don't know the status of the project.

**Comment by villesau** [comment]
Thanks for the response!

To me the other project looks pretty much abandonware unfortunately. It's not even available in IntelliJ plugins -section. I might still give it a try though!

Note that even syntax errors are not reported. That's something that could be solved even without Merlin I think.

I definitely understand the prioritization aspect. If you need more contributors, I'd recommend to document the architecture and internals of the plugin somehow, as well as "getting started" kind of stuff: Links to some basic IntelliJ plugin tutorials etc. NodeJS has very good approach to welcome new developers by having "good first issue", "code and learn" and "help wanted" labels, see: https://github.com/nodejs/node/issues . These would make the barrier to contribute much lower.

I'm pretty sure that OCaml community would be happy to help if it would be made easy!

**Comment by giraud** [comment]
closing this issue: doc has been added, and ocaml problems are reported on other issues alraedy
